local vim = vim
vim.opt.autoindent = true
vim.opt.tabstop = 4
vim.opt.relativenumber = true
vim.wo.number = true
vim.opt.shiftwidth = 4
vim.opt.smarttab = true
vim.opt.softtabstop = 4
vim.opt.mouse = 'a'
vim.opt.hidden = true
vim.opt.signcolumn = 'yes'
vim.opt.termguicolors = true
vim.opt.cursorline = true
vim.opt.clipboard = vim.o.clipboard .. "unnamedplus"
vim.opt.scrolloff = 5
vim.opt.wrap = false
vim.opt.updatetime = 300
